# Generated by Django 5.2.6 on 2025-09-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='colorsmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='equipmentsmodel',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='modificationmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='optionpropertiesmodel',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='options',
            name='property',
        ),
        migrations.AddField(
            model_name='optionpropertiesmodel',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.options'),
        ),
    ]
