# Generated by Django 5.2.6 on 2025-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brandmodel_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsmodel',
            name='exterior_colors',
            field=models.ManyToManyField(blank=True, related_name='exterior_colors', to='main.colorsmodel'),
        ),
        migrations.AlterField(
            model_name='equipmentsmodel',
            name='interior_colors',
            field=models.ManyToManyField(blank=True, related_name='interior_colors', to='main.colorsmodel'),
        ),
    ]
